### PR TITLE
fix: propagate coverage param through predict/fit_predict/fit_predict…

### LINKED ISSUE #205: [BUG] fit_predict_async silently drops coverage parameter — prediction intervals never returned for async jobs
## Summary
`executor.fit_predict_async()` has no `coverage` parameter in its signature (executor.py:249), but `fit_predict_async_tool` tries to pass `coverage=coverage` to it (fit_predict.py:183). The argument is silently dropped, and `self.predict()` is called without `coverage` (executor.py:343), so prediction intervals are **never returned** for async jobs even when explicitly requested.

## Root Cause
`fit_predict_async` signature (executor.py:249):
```python
async def fit_predict_async(self, handle_id, dataset, horizon=12, job_id=None):
    # no coverage param!

### PR DESCRIPTION
**Pull request by rupeshca007**
## Summary

Fixes #205

`executor.predict()` and `executor.fit_predict()` were missing the `coverage` parameter entirely, and `executor.fit_predict_async()` had no `coverage` in its signature. Calling `fit_predict_async_tool(coverage=0.9)` silently dropped the argument — prediction intervals were never computed for async jobs.

## Changes (single file: `src/sktime_mcp/runtime/executor.py`)

1. Added `coverage` param to `executor.predict()` with prediction interval computation
2. Added `coverage` param to `executor.fit_predict()` and forwarded it to `self.predict()`
3. Added `coverage` param to `executor.fit_predict_async()` and forwarded it to `self.predict()`

## Testing

- `test_async_fit_predict` now passes (was failing with `TypeError: Executor.predict() got an unexpected keyword argument 'coverage'`)
- All 70 other tests continue to pass

## Type of Change
- [x] Bug fix (non-breaking)

### CODE REVIEW

**Comment by rupeshca007** [comment]
"CI failures are pre-existing on main — tracked in #170/#171. My change only touches executor.py."

**Comment by Shashankss1205** [comment]
Since then the tool surface was consolidated: fit_predict/fit_predict_async are gone, replaced by separate fit and predict tools with a run_async flag, and predict already accepts mode='predict_interval' with coverage (and predict_quantiles with alpha). The code this PR patches no longer exists. Closing; #205 is closed as well.
